version: 2

sources:
  - name: flashing_detection_source_market_data
    database: "{{ env_var('PROJECT_ID') }}"
    schema: "{{ env_var('FLASHING_BQ_MARKET_DATA') }}"
    #loaded_at_field: _loaded_at # configure for all sources

    tables:
      - name: nbbo
        description: Table containing national best bids and offers
        #loaded_at_field: updated_at # override source defaults
        columns:
          - name: trade_date
            description: Trade Date
            tests:
              - not_null
          - name: timestamp
            description: Trade timestamp
            tests:
              - not_null
          - name: symbol
            description: Financial instrument of bid or ask
            tests:
              - not_null
          - name: bid
            description: Bid dollar value
          - name: bid_size
            description: Quantity being bid
          - name: ask
            description: Ask dollar value
          - name: ask_size
            description: Quantity being asked

  - name: flashing_detection_source_order_data
    database: "{{ env_var('PROJECT_ID') }}"
    schema: "{{ env_var('FLASHING_BQ_ORDER_DATA') }}"
    #loaded_at_field: _loaded_at # configure for all sources

    tables:
      - name: orders
        description: Table containing all orders submitted to the market
        #loaded_at_field: updated_at # override source defaults
        columns:
          - name: trade_date
            description: Date of order
            tests:
              - not_null
          - name: timestamp
            description: Order timestamp
            tests:
              - not_null
          - name: trading_model
            #!!TODO
            description: UPDATEME
            tests:
              - accepted_values:
                  #!!TODO
                  values: ['UPDATEME']
          - name: account
            #!!TODO
            description: UPDATEM
            tests:
              - not_null
          - name: order_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: event
            #!!TODO
            description: UPDAETME
            tests:
              - accepted_values:
                  #!!TODO
                  values: ['UPDATEME']
          - name: symbol
            description: Financial instrument for the order
            tests:
              - not_null
          - name: exchange
            description: Financial exchange hosting the order
            tests:
              - not_null
              - accepted_values:
                  #!!TODO
                  values: ['UPDATEME']
          - name: side
            description: Buy or Sell
            tests:
              - not_null
              - accepted_values:
                  #!!TODO
                  values: ['UPDATEME']
          - name: size
            description: Size of order
            tests:
              - not_null
          - name: price
            description: Price of order
            tests:
              - not_null
          - name: tif
            #!!TODO
            description: UPDATEME
            tests:
              - not_null
          - name: prev_size
            #!!TODO
            description: UPDATEME
            tests:
              - not_null
          - name: prev_price
            #!!TODO
            description: UPDATEME
            tests:
              - not_null
          - name: fill_size
            #!!TODO
            description: UPDATEME
            tests:
              - not_null
          - name: fill_price
            #!!TODO
            description: UPDATEME
            tests:
              - not_null
          - name: exec_id
            #!!TODO
            description: UPDATEME
            tests:
              - unique
              - not_null